- id: doi:10.1016/j.xpro.2022.101784
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166722006645-fx1.jpg
  tags:
    - Primary Research

- id: doi:10.4049/jimmunol.2200145
  image: https://aai.silverchair-cdn.com/aai/content_public/journal/jimmunol/209/5/10.4049_jimmunol.2200145/1/m_ji2200145f2.png
  tags:
    - Primary Research

- id: doi:10.1016/j.xcrm.2022.100614
  image: https://github.com/EllisLabUK/EllisLab.github.io/blob/main/images/2022CellRepMed.jpg?raw=true
  tags:
    - Primary Research
    
- id: doi:10.1038/s41576-021-00329-9
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41576-021-00329-9/MediaObjects/41576_2021_329_Fig1_HTML.png?as=webp
  tags:
    - Review

- id: doi:10.1038/s43018-020-00155-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs43018-020-00155-8/MediaObjects/43018_2020_155_Fig1_HTML.png
  tags:
    - Commentary
    
- id: doi:10.1182/blood.2020006372
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/136/15/10.1182_blood.2020006372/2/m_bloodbld2020006372absf1.png?Expires=1673664222&Signature=5MKSjLqNz-ku52JQvXxJyP9H3GAWU4tTZOYwWG1bowtL3UmARNsQXpEx2CxetAoByc8XqR9I-O4nCWU78RSLnNHG95B5fgyJn4sbw9bbtc0K06pIY0zVCFoiOgJcMu1xIQefT5dSyMKokdPo6~Sj4ToK~CwZwa1gv4AVBwJycw~zcHielxBL0CaNd81whxJ~tCU95OFuHpuEWxkZEmbj6hQVI3y1BMAb1RlA4p9-admm~iyaEeKbuXLwREfgohXudud7oBpTfkRhtGsvbrAh9N0W2gmZeRds-QZRsFpOd9Wo79eMFXlwZ4zKfzW8DfvNDLRl1j8pBBEAy1iXkaxeOQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - Primary Research

- id: doi:10.1038/s41577-018-0042-2
  image: https://media.springernature.com/w200/springer-static/cover-hires/journal/41577/18/10
  tags:
    - Review
    
- id: doi:10.1177/1744806916647055
   image: https://journals.sagepub.com/cms/10.1177/1744806916647055/asset/images/large/10.1177_1744806916647055-fig1.jpeg
   tags:
     - Primary Resarch
   
- id: doi:10.1007/s10620-015-3700-2
    image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs10620-015-3700-2/MediaObjects/10620_2015_3700_Fig2_HTML.gif?as=webp
    tags:
      - Primary Research
      
- id: doi:10.1002/eji.201343571
    image: https://onlinelibrary.wiley.com/cms/asset/d6d2f893-4ace-4d92-9e0d-a84dfacbfdc1/eji2774-fig-0003-m.png
    tags:
      - Primary Research
